### PR TITLE
Release/3.1.0

### PR DESCRIPTION
**Pull request by 0xean**
IOS and Android Release branch - feel free to add issue discovered during testing here

### CODE REVIEW

**Comment by woodenfurniture** [comment]
Tested on Pixel 4a with Android 13, not issues found.

**Review by woodenfurniture — APPROVED** [review]
Tested on Pixel 4a with Android 13, no issues found.

**Comment by 0xean** [comment]
IOS isn't working, 2 testers have reported infinite spinners when loading even after fresh installs. Will need to debug further

**Comment by 0xean** [comment]
IOS working with build 325

**Comment by 0xean** [comment]
taking a preliminary look at this now

**Comment by 0xean** [comment]
Looks like somewhere along the way we lost the permissions in ios, adding back solved it locally, pushing a build to confirm

**Comment by 0xean** [comment]
@gomesalexandre - I looked over that commit a bit and saw we also removed this line https://github.com/shapeshift/mobile-app/commit/d9915f5b9b1a9d829902d017ee123993cbf99382#diff-dd86ee93a69fbc92bc90d1c7ea3166b81e5dbb123bcc7426902e3efe6934fc39L59

IIRC the intent was to allow the app to update in the background, any reason to not add that back?

**Comment by NeOMakinG** [comment]
> @gomesalexandre - I looked over that commit a bit and saw we also removed this line [d9915f5#diff-dd86ee93a69fbc92bc90d1c7ea3166b81e5dbb123bcc7426902e3efe6934fc39L59](https://github.com/shapeshift/mobile-app/commit/d9915f5b9b1a9d829902d017ee123993cbf99382#diff-dd86ee93a69fbc92bc90d1c7ea3166b81e5dbb123bcc7426902e3efe6934fc39L59)
> 
> IIRC the intent was to allow the app to update in the background, any reason to not add that back?

I think all this file has been changed due to a complete rebuild after the udpate

We need to bring back every permissions we removed to stay ISO with the old app

**Comment by 0xean** [comment]
I am adding back a few more items to the info.plist and then will push one last ios build. Mainly just adding the background fetch back and a flag to about encryption to avoid clicking buttons in app store.

**Pull request merged**
